//GET TODO LIST
export const GET_LIST_START="GET_LIST_START";
export const GET_LIST_SUCCESS="GET_LIST_SUCCESS";
export const GET_LIST_FAILED="GET_LIST_FAILED"; 

export const ADD_TODO_START="ADD_TODO_START"; 
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS"; 
export const ADD_TODO_FAILED="ADD_TODO_FAILED"; 


export const VIEW_TODO_FAILED="VIEW_TODO_FAILED"; 
export const VIEW_TODO_SUCCESS="VIEW_TODO_SUCCESS"; 
export const VIEW_TODO_START="VIEW_TODO_START"; 

export const UPDATE_TODO_SUCCESS="UPDATE_TODO_SUCCESS"; 
export const UPDATE_TODO_START="UPDATE_TODO_START"; 
export const UPDATE_TODO_FAILED="UPDATE_TODO_FAILED"; 


export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS"; 
export const DELETE_TODO_START="DELETE_TODO_START"; 
export const DELETE_TODO_FAILED="DELETE_TODO_FAILED"; 





