//GET TODO LIST
export const GET_LIST_START="GET_LIST_START";
export const GET_LIST_SUCCESS="GET_LIST_SUCCESS";
export const GET_LIST_FAILED="GET_LIST_FAILED"; 

export const ADD_TODO_START="ADD_TODO_START"; 
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS"; 
export const ADD_TODO_FAILED="ADD_TODO_FAILED"; 


export const VIEW_TODO_FAILED="VIEW_TODO_FAILED"; 
export const VIEW_TODO_SUCCESS="VIEW_TODO_SUCCESS"; 
export const VIEW_TODO_START="VIEW_TODO_START"; 
